# Generated by Django 4.2 on 2023-05-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_alter_movie_options_rename_age_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='discription',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
